In [2]:
import mylibrary as ml

In [3]:
ml.mySign('김현진')

Power of 김현진


In [4]:
my_sum, my_avg = ml.sum_avg(70,50,80)

In [5]:
print(my_sum,my_avg)

200 66.66666666666667


In [6]:
import numpy as np

In [9]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
arr2.shape    # 2행 3열

(2, 3)

In [11]:
print(arr2.size)   # 사이즈 확인

6


In [12]:
print(arr2.dtype)   # 데이터 타입 확인

int32


In [14]:
print(arr2.ndim)   # 차원 확인

2


In [ ]:
B = for i in range 10 :
        for j in range 10 :
            for k in range 10 :
                i*j*k

In [21]:
array3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [58]:
print(array3.size)
print(f'타입 : {array3.dtype}')
print(f'차원 : {array3.ndim}')
print(array3.shape)

8
타입 : int32
차원 : 3
(2, 2, 2)


In [27]:
arr_zeros = np.zeros((3,4))
arr_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
arr_ones = np.ones((3,4))
arr_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [29]:
arr_full = np.full((5,7),7)
arr_full

array([[7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7]])

In [31]:
list = []
for i in range(1,51) :                     # list에 넣는 작업. 1.
    list.append(i)
print(list)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]


In [32]:
arr = np.array(list)               #list를 array로 만드는 작업.  2.
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [34]:
arr = np.arange(1,51)   # 위 두개 과정을 축소 ****
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [36]:
arr = np.arange(1,51,10)  # 배열 형성 응용 (10씩 더하여)
arr

array([ 1, 11, 21, 31, 41])

In [37]:
arr_type = np.array([1.2,2.3,3.4], dtype=np.int64)
arr_type

array([1, 2, 3], dtype=int64)

##  ------------------------------------------------------------------------------------------

In [40]:
a_3d = [[[ 0 , 1 , 2 , 3],
         [ 4  ,5  ,6  ,7],
         [ 8 , 9 ,10 ,11]],
 
         [[12 ,13 ,14, 15],
         [16 ,17 ,18 ,19],
        [20 ,21, 22 ,23]]]

In [46]:
A1 = np.array(a_3d)
A1

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [57]:
print(A1.size)
print(A1.dtype)
print(A1.shape)
print(A1.ndim)

24
int32
(2, 3, 4)
3


In [61]:
a_4d = np.arange(24)
a_4d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [62]:
a_4d = np.arange(24).reshape((2, 3, 4))
a_4d   # 바깥 쪽 부터 안쪽으로 세어 간다. 2 --> 3 --> 4

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

##  ------------------------------------------------------------------------------------------

In [63]:
arr_type = arr_type.astype('float64')
arr_type

array([1., 2., 3.])

In [64]:
arr_type.dtype

dtype('float64')

In [65]:
arr = np.random.rand(2,3)
arr

array([[0.33182917, 0.2619912 , 0.92793458],
       [0.41866472, 0.16775123, 0.25275036]])

In [66]:
arr = np.random.randint(2,10)
arr

9

In [69]:
arr = np.random.randint(2,10, size=(2,3,4))
arr

array([[[5, 3, 9, 2],
        [7, 7, 2, 6],
        [2, 8, 2, 9]],

       [[5, 4, 9, 9],
        [7, 8, 5, 5],
        [7, 8, 8, 3]]])

In [71]:
arr+A1

array([[[ 5,  4, 11,  5],
        [11, 12,  8, 13],
        [10, 17, 12, 20]],

       [[17, 17, 23, 24],
        [23, 25, 23, 24],
        [27, 29, 30, 26]]])

In [72]:
arr*A1

array([[[  0,   3,  18,   6],
        [ 28,  35,  12,  42],
        [ 16,  72,  20,  99]],

       [[ 60,  52, 126, 135],
        [112, 136,  90,  95],
        [140, 168, 176,  69]]])

In [74]:
data = np.loadtxt('height_weight.txt',delimiter=',')
data

array([[175.2, 180.3, 175. , 169.2, 185.2, 188. , 177.6, 178.2, 177. ,
        179. ],
       [ 65.6,  88. ,  79.2,  69.3,  55. ,  71.2,  73. ,  68.9,  74. ,
         82. ]])

In [75]:
data.shape

(2, 10)

In [76]:
height = data[0]*0.01
height

array([1.752, 1.803, 1.75 , 1.692, 1.852, 1.88 , 1.776, 1.782, 1.77 ,
       1.79 ])

In [77]:
weight = data[1]

In [80]:
BMI = weight/(height**2)              # Numpy를 사용하면 for문으로 일일이 계산을 해줘야는 수고를 덜 수 있다.
BMI

array([21.37153104, 27.07018468, 25.86122449, 24.20652885, 16.03543423,
       20.14486193, 23.14392095, 21.69720651, 23.62028791, 25.59220998])

In [81]:
arr2 = np.arange(50).reshape(5,10)
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [82]:
arr2[:2,:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [88]:
arr2[2:5,5:9]

array([[25, 26, 27, 28],
       [35, 36, 37, 38],
       [45, 46, 47, 48]])

In [91]:
arr2[[2,3],[2,3]]

array([22, 33])

In [100]:
arr2[[1,4],[1,2]]   #알겠는데 왜?

array([11, 42])

In [117]:
C = [3.423423,5,32,6]
C[::-1]

[6, 32, 5, 3.423423]

In [118]:
C[::2]

[3.423423, 32]

In [119]:
C[::3]

[3.423423, 6]

In [120]:
name = np.array(['원호','명호','병관','명진'])
bol = np.array([False,True,True,False])

In [121]:
name[bol]         # 흔히 마스킹 기능과 비슷함.

array(['명호', '병관'], dtype='<U2')

In [124]:
score = np.array([[50,50],[60,60],[70,70],[80,80]])
name=='명호'

array([False,  True, False, False])

In [126]:
score[name=="명호"]    #배열로 대입한다는 것은 [] 로 해야함.

array([[60, 60]])

In [131]:
arr = np.random.randint(1,10, size=(4,7))
arr

array([[9, 2, 7, 7, 1, 1, 4],
       [8, 5, 1, 9, 5, 3, 3],
       [3, 2, 8, 7, 5, 3, 3],
       [4, 8, 4, 2, 1, 7, 5]])

In [132]:
arr.sum()

127

In [133]:
np.sum(arr)

127

In [134]:
data = np.loadtxt('ratings.txt', delimiter='::', dtype='int')
data

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       ...,
       [     6040,       562,         5, 956704746],
       [     6040,      1096,         4, 956715648],
       [     6040,      1097,         4, 956715569]])

In [135]:
print(data.ndim)
print(data.shape)
print(data.size)

2
(1000209, 4)
4000836


In [140]:
전체평점 = np.mean(data[:,2])
전체평점

3.581564453029317

In [143]:
user_id = np.unique(data[:,0])   # 중복제거
user_id

array([   1,    2,    3, ..., 6038, 6039, 6040])

In [144]:
print(user_id.shape)   #행,열 형태

(6040,)


In [149]:
data[:,0]  #전체행 0번 열 전부 표시

array([   1,    1,    1, ..., 6040, 6040, 6040])

In [147]:
data[:,0] == 1   #전체행 0번 열 중에서 1번은 참으로 만들기

array([ True,  True,  True, ..., False, False, False])

In [148]:
data[data[:,0] == 1]

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       [        1,      3408,         4, 978300275],
       [        1,      2355,         5, 978824291],
       [        1,      1197,         3, 978302268],
       [        1,      1287,         5, 978302039],
       [        1,      2804,         5, 978300719],
       [        1,       594,         4, 978302268],
       [        1,       919,         4, 978301368],
       [        1,       595,         5, 978824268],
       [        1,       938,         4, 978301752],
       [        1,      2398,         4, 978302281],
       [        1,      2918,         4, 978302124],
       [        1,      1035,         5, 978301753],
       [        1,      2791,         4, 978302188],
       [        1,      2687,         3, 978824268],
       [        1,      2018,         4, 978301777],
       [        1,      3105,         5, 97830

In [160]:
list1 = []

for user in user_id:
    user_mean = data[data[ : , 0] == user]  # 이 항이 바로 위에 것
    user_mean = user_mean[: ,2].mean()  # 2번열만 지정한 후 평균
    list1.append([user, user_mean])

In [163]:
list2 = []

for user in user_id:
    user_mean = data[data[ : , 0] == user, 2].mean()   # list 1 이랑 같은 결과
    list2.append([user, user_mean])

In [161]:
data[1]

array([        1,       661,         3, 978302109])

In [162]:
list1

[[1, 4.188679245283019],
 [2, 3.7131782945736433],
 [3, 3.9019607843137254],
 [4, 4.190476190476191],
 [5, 3.1464646464646466],
 [6, 3.9014084507042255],
 [7, 4.32258064516129],
 [8, 3.884892086330935],
 [9, 3.7358490566037736],
 [10, 4.114713216957606],
 [11, 3.2773722627737225],
 [12, 3.8260869565217392],
 [13, 3.388888888888889],
 [14, 3.32],
 [15, 3.3233830845771144],
 [16, 3.0285714285714285],
 [17, 4.075829383886256],
 [18, 3.6491803278688524],
 [19, 3.5725490196078433],
 [20, 4.083333333333333],
 [21, 2.909090909090909],
 [22, 3.0673400673400675],
 [23, 3.3157894736842106],
 [24, 3.948529411764706],
 [25, 3.7411764705882353],
 [26, 2.96],
 [27, 4.171428571428572],
 [28, 3.7570093457943927],
 [29, 3.5833333333333335],
 [30, 3.488372093023256],
 [31, 3.73109243697479],
 [32, 3.625],
 [33, 3.498721227621483],
 [34, 3.8658536585365852],
 [35, 3.54040404040404],
 [36, 4.199430199430199],
 [37, 3.69811320754717],
 [38, 3.58],
 [39, 3.564516129032258],
 [40, 3.4479166666666665],
 [41, 

In [176]:
list1[3][1]

4.190476190476191

In [181]:
for i in range(0,len(list1)+1) :
    if list1[i][1] >= 4 :
        print(list1[i][0])

1
4
7
10
17
20
27
36
43
46
53
54
55
64
65
67
69
74
75
76
81
82
86
88
91
97
101
103
105
106
109
112
121
124
125
126
128
129
130
138
150
152
153
156
158
161
162
164
171
177
183
184
186
187
189
196
205
210
213
215
220
222
228
230
231
233
234
235
239
244
246
248
252
255
257
259
265
266
270
274
275
283
285
288
291
297
299
300
307
309
311
313
316
320
322
325
330
332
336
339
341
343
345
346
356
366
367
372
374
375
376
379
381
382
399
404
408
412
413
417
420
421
427
434
437
444
446
447
450
451
452
455
466
469
472
473
485
486
494
496
502
503
505
514
518
521
523
525
527
529
530
537
538
543
553
564
567
568
574
577
582
583
584
586
588
589
590
592
594
597
605
606
607
609
615
617
623
625
626
630
634
635
636
638
640
641
642
645
653
657
661
664
671
674
681
682
690
691
703
711
714
716
725
733
739
740
750
755
758
760
761
764
767
768
775
784
786
790
797
806
809
811
814
815
817
829
831
833
834
838
840
848
852
857
858
863
864
875
878
879
882
884
885
894
898
902
914
917
926
928
931
932
942
943
946
951
953
9

IndexError: list index out of range

In [164]:
list2

[[1, 4.188679245283019],
 [2, 3.7131782945736433],
 [3, 3.9019607843137254],
 [4, 4.190476190476191],
 [5, 3.1464646464646466],
 [6, 3.9014084507042255],
 [7, 4.32258064516129],
 [8, 3.884892086330935],
 [9, 3.7358490566037736],
 [10, 4.114713216957606],
 [11, 3.2773722627737225],
 [12, 3.8260869565217392],
 [13, 3.388888888888889],
 [14, 3.32],
 [15, 3.3233830845771144],
 [16, 3.0285714285714285],
 [17, 4.075829383886256],
 [18, 3.6491803278688524],
 [19, 3.5725490196078433],
 [20, 4.083333333333333],
 [21, 2.909090909090909],
 [22, 3.0673400673400675],
 [23, 3.3157894736842106],
 [24, 3.948529411764706],
 [25, 3.7411764705882353],
 [26, 2.96],
 [27, 4.171428571428572],
 [28, 3.7570093457943927],
 [29, 3.5833333333333335],
 [30, 3.488372093023256],
 [31, 3.73109243697479],
 [32, 3.625],
 [33, 3.498721227621483],
 [34, 3.8658536585365852],
 [35, 3.54040404040404],
 [36, 4.199430199430199],
 [37, 3.69811320754717],
 [38, 3.58],
 [39, 3.564516129032258],
 [40, 3.4479166666666665],
 [41, 

In [136]:
np.savetxt('user_id_mean.csv', list, delimiter=',', fmt='%.3f')